### ISSUE TITLE
Room description not being persisted

### ISSUE THREAD

**Issue by rizblie** [gameontext/gameon-room-java#29]
I have tried adding a room description but it never seems to save it. When I go back to the Edit Room page the description has disappeared.

**Comment by cfsworkload** [comment]
Hmm. Two things:

A) there is what is persisted in the map, which is easiest modified by the UI (edit rooms)

B) to persist room description changes from the room, you will need to make an API call to the map service.

C) including the updated description in the generated location response will push the information to the Client UI

------ 

Erin Schnabel <schnabel@us.ibm.com>
WebSphere Liberty developer/maven/evangelist and Microservices Architect
845.435.5648 / 8.295.5648
i ♥ liberty

**Comment by cfsworkload** [comment]
Ok. That is a different problem.. let me look.

------ 

Erin Schnabel <schnabel@us.ibm.com>
WebSphere Liberty developer/maven/evangelist and Microservices Architect
845.435.5648 / 8.295.5648
i ♥ liberty

**Comment by ebullient** [comment]
Do you have a shared secret shown at the top of the room management page? (line after `Use the following secret for room registration:`)

**Comment by ebullient** [comment]
This one has been nipped. Need a follow-on for fetching description from map client.
