### ISSUE TITLE
Text in set up step points to non-existent Edit Profile button

### ISSUE THREAD

**Issue by donbourne** [gameontext/gameon-room-java#3]
https://developer.ibm.com/architecture/gallery/createMicroservices/walkthrough/GetGameOnCreds page has mistake in step 3.  There is no Edit Profile button.

**Comment by ebullient** [comment]
@osowski -- was the above link built from JSON stashed somewhere? none of the walkthrough text in markdown has that language in it.

**Comment by osowski** [comment]
Not sure how this was generated originally.  I would imagine it was written or borrowed from markdown a long time ago.  

Does https://github.com/gameontext/gameon-room-java have the desired wording right now?

**Comment by ebullient** [comment]
All of the README.md files use the same wording for step 3.

**Comment by ebullient** [comment]
@osowski -- this is done now, right?

**Comment by cfsworkload** [comment]
Yep, this is all done.
 
Rick OsowskiSenior Technical Offering ManagerIBM Cloud Solution Engineeringosowski@us.ibm.comCell:  (919) 608-8935
 
 
----- Original message -----From: Erin Schnabel <notifications@github.com>To: gameontext/gameon-room-java <gameon-room-java@noreply.github.com>Cc:Subject: Re: [gameontext/gameon-room-java] Text in set up step points to non-existent Edit Profile button (#3)Date: Wed, Jun 8, 2016 7:07 PM 
@osowski -- this is done now, right?
