### ISSUE TITLE
Command to run maven install has unnecessary slashes

### ISSUE THREAD

**Issue by biscuitsarehot** [gameontext/gameon-room-java#5]
The command to run mvn install to push the app has slashes after each argument

**Comment by ebullient** [comment]
It is true that the slashes are unnecessary.  We have them present in the readme for readability (where cut and paste to the command line or a shell script would still work).

Did it cause a problem? or just commenting on their being extraneous..

**Comment by ebullient** [comment]
Resolved via commit f70db6c046144eda5341bbb3dfd350fd898ff05c
